"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, ChevronRight, ExternalLink, MapPin, Minus, RefreshCw, ShieldAlert, TrendingDown, TrendingUp, GitCompareArrows, CheckCircle2, CircleSlash2 } from "lucide-react";

type E={id:string;title:string;category:string|null;geography:string|null;publishedAt:string|null;relevanceScore:number|null;sourceUrl?:string|null};
type Shift={theme:string;current30:number;previous30:number;direction:'accelererar'|'stabil'|'avtar'|'ny';delta:number};
type TrailItem={eventId:string;title:string;publishedAt:string|null;geography:string|null;category:string|null;sourceUrl?:string|null;signalType:string;strength:'stark'|'medel'|'svag';reason:string};
type Trail={actor:string;localSignals30d:number;localSignals90d:number;strongestSignal:'stark'|'medel'|'svag'|null;summary:string;changes:string[];items:TrailItem[]};
type ChangeEvidence={eventId:string;title:string;publishedAt:string|null;category:string|null;geography:string|null;sourceUrl?:string|null};
type ChangePicture={headline:string;summary:string;confidence:'hög'|'medel'|'låg';supportCount:number;independentDomains:number;changes:{label:string;direction:'ökar'|'minskar'|'nytt'|'stabilt';detail:string}[];supportingEvidence:ChangeEvidence[];counterEvidence:ChangeEvidence[];caveat:string};
type A={name:string;eventCount30d:number;eventCount90d:number;averageScore:number;momentum:'accelererar'|'stabil'|'avtar';latestEventAt:string|null;independentSourceDomains:number;categories:{name:string;count:number}[];geographies:{name:string;count:number}[];themeShifts:Shift[];headline:string;interpretation:string;watchNext:string[];timeline:E[];trail:Trail;changePicture:ChangePicture};
type Payload={historyEnabled:boolean;reason:string|null;eventCount:number;actors:A[];disclaimer:string};
function shiftText(s:Shift){return s.direction==='ny'?'nytt tema':s.direction==='accelererar'?'accelererar':s.direction==='avtar'?'avtar':'stabilt'}
export default function ActorWatchlist({actors}:{actors:string[]}){
 const actorKey=useMemo(()=>actors.join(','),[actors]); const [data,setData]=useState<Payload|null>(null); const [selected,setSelected]=useState(''); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const qs=new URLSearchParams();if(actorKey)qs.set('actors',actorKey);const r=await fetch(`/api/actor-watchlist?${qs.toString()}`,{cache:'no-store'});const d=await r.json() as Payload;setData(d);setSelected(prev=>d.actors.some(x=>x.name===prev)?prev:(d.actors[0]?.name??''));}finally{setLoading(false)}};
 useEffect(()=>{void load()},[actorKey]); const current=data?.actors.find(x=>x.name===selected)??data?.actors[0]; const Momentum=current?.momentum==='accelererar'?TrendingUp:current?.momentum==='avtar'?TrendingDown:Minus;
 return <section className="actorWatch"><div className="actorWatchHead"><div><p className="eyebrow"><Building2 size={13}/> KONKURRENTSPÅR · v2.17</p><h2>Vad gör aktörerna – och vad verkar vara på väg att hända?</h2><p>Historik, temaförflyttningar och tidiga lokala signaler samlas per konkurrent.</p></div><button className="iconButton" onClick={()=>void load()} aria-label="Uppdatera aktörsbild"><RefreshCw size={17} className={loading?'spin':''}/></button></div>
 {!data?.historyEnabled&&<div className="emptyState">Historik krävs för en källgrundad aktörsbild. {data?.reason}</div>}
 {data?.historyEnabled&&data.actors.length===0&&<div className="emptyState">Inga bevakade aktörer har ännu tillräcklig historik. Lägg till aktörer i bevakningsprofilen eller samla fler källhändelser.</div>}
 {current&&<><div className="actorTabs">{data?.actors.map(a=><button key={a.name} className={a.name===current.name?'active':''} onClick={()=>setSelected(a.name)}><strong>{a.name}</strong><span>{a.eventCount30d} händelser · {a.trail.localSignals30d} lokala signaler</span></button>)}</div>
 <div className="actorDashboard"><div className="actorSummary"><div className="actorTitle"><div><h3>{current.name}</h3><span className={`momentum ${current.momentum}`}><Momentum size={14}/>{current.momentum}</span></div><p>{current.interpretation}</p></div><div className="actorStats"><span><strong>{current.eventCount30d}</strong>30 dagar</span><span><strong>{current.trail.localSignals30d}</strong>lokala 30 d</span><span><strong>{current.averageScore}</strong>snittscore</span><span><strong>{current.independentSourceDomains}</strong>källdomäner</span></div></div>

 <section className="changePicture"><div className="changePictureHead"><div><small className="sectionKicker">VAD HAR FAKTISKT ÄNDRATS?</small><h3><GitCompareArrows size={16}/> Konkurrentens förändringsbild</h3></div><span className={`changeConfidence ${current.changePicture.confidence}`}>{current.changePicture.confidence} säkerhet</span></div><h4>{current.changePicture.headline}</h4><p className="changeSummary">{current.changePicture.summary}</p><div className="changeMeta"><span><strong>{current.changePicture.supportCount}</strong> stödjande händelser</span><span><strong>{current.changePicture.independentDomains}</strong> oberoende domäner</span><span><strong>{current.changePicture.counterEvidence.length}</strong> motbevis</span></div>
 {current.changePicture.changes.length>0?<div className="changeList">{current.changePicture.changes.map(change=><div key={`${change.label}-${change.direction}`} className={`changeItem ${change.direction}`}><span>{change.direction}</span><div><strong>{change.label}</strong><p>{change.detail}</p></div></div>)}</div>:<p className="smallText">Ingen tillräckligt tydlig förändring mot föregående 30-dagarsperiod ännu.</p>}
 <div className="evidenceGrid"><div><small className="sectionKicker"><CheckCircle2 size={12}/> STÖDJANDE HÄNDELSER</small>{current.changePicture.supportingEvidence.length?current.changePicture.supportingEvidence.slice(0,4).map(e=><article key={e.eventId}><div><strong>{e.title}</strong><small>{e.publishedAt?new Date(e.publishedAt).toLocaleDateString('sv-SE'):'Datum saknas'}{e.geography?` · ${e.geography}`:''}</small></div>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={13}/></a>}</article>):<p className="smallText">Inget stödjande underlag i perioden.</p>}</div><div><small className="sectionKicker"><CircleSlash2 size={12}/> MOTBEVIS / BROMSAR</small>{current.changePicture.counterEvidence.length?current.changePicture.counterEvidence.map(e=><article key={e.eventId}><div><strong>{e.title}</strong><small>{e.publishedAt?new Date(e.publishedAt).toLocaleDateString('sv-SE'):'Datum saknas'}{e.geography?` · ${e.geography}`:''}</small></div>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={13}/></a>}</article>):<p className="smallText">Inga tydliga motbevis fångade i senaste 30 dagar.</p>}</div></div><p className="changeCaveat">{current.changePicture.caveat}</p></section>

 <section className="competitorTrail"><div className="competitorTrailHead"><div><small className="sectionKicker">TIDIGA LOKALA SIGNALER</small><h3><MapPin size={16}/> Konkurrentens spår</h3></div>{current.trail.strongestSignal&&<span className={`trailStrength ${current.trail.strongestSignal}`}>{current.trail.strongestSignal} signalnivå</span>}</div><p className="trailSummary">{current.trail.summary}</p>
 {current.trail.changes.length>0&&<div className="trailChanges">{current.trail.changes.map(change=><div key={change}><ShieldAlert size={14}/><span>{change}</span></div>)}</div>}
 {current.trail.items.length>0?<div className="trailItems">{current.trail.items.slice(0,6).map(item=><article key={item.eventId}><div className="trailDate"><time>{item.publishedAt?new Date(item.publishedAt).toLocaleDateString('sv-SE'):'Datum saknas'}</time><span className={`signalPill ${item.strength}`}>{item.signalType}</span></div><div><strong>{item.title}</strong><p>{item.reason}</p><small>{item.geography??'Geografi saknas'}{item.category?` · ${item.category}`:''}</small></div>{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer" aria-label="Öppna källa"><ExternalLink size={14}/></a>}</article>)}</div>:<p className="smallText">Inga lokala försignaler kan beläggas i den tillgängliga historiken ännu.</p>}
 <p className="trailCaveat">Det här är observerade försignaler. Flera träffar kan höra ihop med samma underliggande ärende och är inte i sig bevis för en beslutad strategi.</p></section>

 <div className="actorColumns"><section><small className="sectionKicker">TEMAFÖRFLYTTNING</small><div className="themeShiftList">{current.themeShifts.length?current.themeShifts.map(s=><div key={s.theme} className={`themeShift ${s.direction}`}><div><strong>{s.theme}</strong><span>{shiftText(s)}</span></div><div><b>{s.current30}</b><small>nu</small><ChevronRight size={13}/><b>{s.previous30}</b><small>föreg.</small></div></div>):<p className="smallText">Inget tydligt temaskifte kan beläggas ännu.</p>}</div></section>
 <section><small className="sectionKicker">BEVAKA HÄRNÄST</small><div className="watchNextList">{current.watchNext.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div><div className="actorMeta"><div><small>Tyngdpunkter</small><p>{current.categories.slice(0,4).map(x=>`${x.name} · ${x.count}`).join('  ·  ')||'Saknas'}</p></div><div><small>Geografi</small><p>{current.geographies.slice(0,4).map(x=>`${x.name} · ${x.count}`).join('  ·  ')||'Ingen tydlig geografi'}</p></div></div></section></div>
 <div className="actorTimeline"><small className="sectionKicker">HELA AKTÖRSTIDSLINJEN</small>{current.timeline.length?current.timeline.map(e=><article key={e.id}><time>{e.publishedAt?new Date(e.publishedAt).toLocaleDateString('sv-SE'):'Datum saknas'}</time><div><strong>{e.title}</strong><span>{e.category??'Övrigt'}{e.geography?` · ${e.geography}`:''}{typeof e.relevanceScore==='number'?` · ${e.relevanceScore}/100`:''}</span></div>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer" aria-label="Öppna källa"><ExternalLink size={14}/></a>}</article>):<p className="smallText">Ingen daterad tidslinje finns ännu.</p>}</div>
 <p className="actorDisclaimer">{data?.disclaimer}</p></div></>}
 </section>
}
