"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, ChevronRight, ExternalLink, Minus, RefreshCw, TrendingDown, TrendingUp } from "lucide-react";

type E={id:string;title:string;category:string|null;geography:string|null;publishedAt:string|null;relevanceScore:number|null;sourceUrl?:string|null};
type Shift={theme:string;current30:number;previous30:number;direction:'accelererar'|'stabil'|'avtar'|'ny';delta:number};
type A={name:string;eventCount30d:number;eventCount90d:number;averageScore:number;momentum:'accelererar'|'stabil'|'avtar';latestEventAt:string|null;independentSourceDomains:number;categories:{name:string;count:number}[];geographies:{name:string;count:number}[];themeShifts:Shift[];headline:string;interpretation:string;watchNext:string[];timeline:E[]};
type Payload={historyEnabled:boolean;reason:string|null;eventCount:number;actors:A[];disclaimer:string};
function shiftText(s:Shift){return s.direction==='ny'?'nytt tema':s.direction==='accelererar'?'accelererar':s.direction==='avtar'?'avtar':'stabilt'}
export default function ActorWatchlist({actors}:{actors:string[]}){
 const actorKey=useMemo(()=>actors.join(','),[actors]); const [data,setData]=useState<Payload|null>(null); const [selected,setSelected]=useState(''); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const qs=new URLSearchParams();if(actorKey)qs.set('actors',actorKey);const r=await fetch(`/api/actor-watchlist?${qs.toString()}`,{cache:'no-store'});const d=await r.json() as Payload;setData(d);setSelected(prev=>d.actors.some(x=>x.name===prev)?prev:(d.actors[0]?.name??''));}finally{setLoading(false)}};
 useEffect(()=>{void load()},[actorKey]); const current=data?.actors.find(x=>x.name===selected)??data?.actors[0]; const Momentum=current?.momentum==='accelererar'?TrendingUp:current?.momentum==='avtar'?TrendingDown:Minus;
 return <section className="actorWatch"><div className="actorWatchHead"><div><p className="eyebrow"><Building2 size={13}/> AKTÖRSWATCHLIST · v1.9</p><h2>Vad gör aktörerna – och åt vilket håll rör de sig?</h2><p>Samlad tidslinje, temaförflyttningar och nästa signaler att hålla utkik efter.</p></div><button className="iconButton" onClick={()=>void load()} aria-label="Uppdatera aktörsbild"><RefreshCw size={17} className={loading?'spin':''}/></button></div>
 {!data?.historyEnabled&&<div className="emptyState">Historik krävs för en källgrundad aktörsbild. {data?.reason}</div>}
 {data?.historyEnabled&&data.actors.length===0&&<div className="emptyState">Inga bevakade aktörer har ännu tillräcklig historik. Lägg till aktörer i bevakningsprofilen eller samla fler källhändelser.</div>}
 {current&&<><div className="actorTabs">{data?.actors.map(a=><button key={a.name} className={a.name===current.name?'active':''} onClick={()=>setSelected(a.name)}><strong>{a.name}</strong><span>{a.eventCount30d} · 30 d</span></button>)}</div>
 <div className="actorDashboard"><div className="actorSummary"><div className="actorTitle"><div><h3>{current.name}</h3><span className={`momentum ${current.momentum}`}><Momentum size={14}/>{current.momentum}</span></div><p>{current.interpretation}</p></div><div className="actorStats"><span><strong>{current.eventCount30d}</strong>30 dagar</span><span><strong>{current.eventCount90d}</strong>90 dagar</span><span><strong>{current.averageScore}</strong>snittscore</span><span><strong>{current.independentSourceDomains}</strong>källdomäner</span></div></div>
 <div className="actorColumns"><section><small className="sectionKicker">TEMAFÖRFLYTTNING</small><div className="themeShiftList">{current.themeShifts.length?current.themeShifts.map(s=><div key={s.theme} className={`themeShift ${s.direction}`}><div><strong>{s.theme}</strong><span>{shiftText(s)}</span></div><div><b>{s.current30}</b><small>nu</small><ChevronRight size={13}/><b>{s.previous30}</b><small>föreg.</small></div></div>):<p className="smallText">Inget tydligt temaskifte kan beläggas ännu.</p>}</div></section>
 <section><small className="sectionKicker">BEVAKA HÄRNÄST</small><div className="watchNextList">{current.watchNext.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div><div className="actorMeta"><div><small>Tyngdpunkter</small><p>{current.categories.slice(0,4).map(x=>`${x.name} · ${x.count}`).join('  ·  ')||'Saknas'}</p></div><div><small>Geografi</small><p>{current.geographies.slice(0,4).map(x=>`${x.name} · ${x.count}`).join('  ·  ')||'Ingen tydlig geografi'}</p></div></div></section></div>
 <div className="actorTimeline"><small className="sectionKicker">AKTÖRSTIDSLINJE</small>{current.timeline.length?current.timeline.map(e=><article key={e.id}><time>{e.publishedAt?new Date(e.publishedAt).toLocaleDateString('sv-SE'):'Datum saknas'}</time><div><strong>{e.title}</strong><span>{e.category??'Övrigt'}{e.geography?` · ${e.geography}`:''}{typeof e.relevanceScore==='number'?` · ${e.relevanceScore}/100`:''}</span></div>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer" aria-label="Öppna källa"><ExternalLink size={14}/></a>}</article>):<p className="smallText">Ingen daterad tidslinje finns ännu.</p>}</div>
 <p className="actorDisclaimer">{data?.disclaimer}</p></div></>}
 </section>
}
