"use client";

import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Building2, ExternalLink, Factory, FileText, Radar, RefreshCw, Scale, TrendingUp } from "lucide-react";

type JobSignal={id:string;competitor:string;title:string;url:string;publishedAt:string;geographies:string[];classification:{strategic:boolean;scale:boolean;operational:boolean;signalStrength:'high'|'medium'|'low'|'unknown'}};
type Timeline={id:string;headline:string;competitors:string[];geographies:string[];firstSeen:string;latestSeen:string;ageDays:number;stage:'first-signal'|'corroborating'|'formal-process'|'decision-or-award'|'execution';direction:'escalating'|'stable'|'cooling';escalationScore:number;interpretationConfidence:'Låg'|'Medel'|'Hög';facts:number;sourceClasses:string[];milestones:Array<{title:string;url:string;source:string;sourceClass:string;publishedAt:string;stage:string}>;watchNext:string[]};
type Discovery={id?:string;title:string;url:string;source:string;publishedAt:string;score:number;competitors:string[];geographies:string[];targetId?:string};
type WebsiteChange={id:string;competitor:string;pageType:'homepage'|'careers';url:string;detectedAt:string;changeRatio:number;importance:'low'|'medium'|'high';addedTerms:string[];removedTerms:string[];addedSnippets?:string[];removedSnippets?:string[];dimensions?:string[];summary:string;assessment?:string;guardrail?:string};
type EntityView={organization:string;aliases:string[];geographies:Array<{label:string;observations:number;latestSeen:string}>;signalClasses:Array<{label:string;observations:number;latestSeen:string}>;sources:Array<{label:string;observations:number;latestSeen:string}>};
type StrategicDelta={competitor:string;theme:'contracts'|'capacity'|'permits'|'planning'|'m-and-a'|'investment'|'pricing'|'jobs'|'legal'|'other';direction:'surging'|'rising'|'stable'|'falling'|'new-pattern';recentSignals:number;baselineSignals:number;recentRate:number;baselineRate:number;ratio:number|null;recentStages:string[];latestObservedAt:string;evidenceCaseKeys:string[];reasons:string[];confidence:'low'|'medium'|'high';guardrail:string};
type EvidenceDrilldown={id:string;competitor:string;theme:StrategicDelta['theme'];claim:string;observedFacts:Array<{title:string;url:string;source:string;publishedAt:string;stage:string;caseKey:string}>;linkLogic:string[];assessment:string[];missingEvidence:string[];evidenceCoverage:{currentCases:number;linkedCases:number;sourceCount:number;hasOriginalLinks:boolean};confidence:'low'|'medium'|'high';guardrails:string[]};
type Payload={strategicDeltas?:StrategicDelta[];evidenceDrilldowns?:EvidenceDrilldown[];strategicDeltaSummary?:{historySource?:'database'|'current-run';historyVerified?:boolean};competitorJobSignals?:JobSignal[];competitorEntityViews?:EntityView[];competitorWebsiteMonitor?:{changes:WebsiteChange[];diagnostics:{checked:number;failed:number;baselinesCreated:number;changesDetected:number;persistence:'process-local';verifiedPages:number}};signalTimelines?:Timeline[];discoveryResults?:Discovery[];activeDiscovery?:{status:string};fetchedAt:string};

function norm(value:string){return value.toLocaleLowerCase('sv-SE').replace(/[^a-z0-9åäö]+/g,' ').trim();}
function actorMatches(value:string,actor:string){const a=norm(actor),v=norm(value);return v===a||v.includes(a)||a.includes(v);}
function stageLabel(stage:Timeline['stage']){return stage==='first-signal'?'Första signal':stage==='corroborating'?'Bekräftas':stage==='formal-process'?'Formell process':stage==='decision-or-award'?'Beslut/tilldelning':'Genomförande';}
function sourceLabel(x:string){return x==='jobs'?'Jobb':x==='municipal'?'Kommun':x==='environmental'?'Miljö/tillstånd':x==='competition'?'Konkurrens':x==='planning'?'Plan/mark':x==='legal'?'Juridik':x==='news'?'Nyheter':x==='authority'?'Myndighet':x;}
function sourceIcon(x:string){return x==='jobs'?BriefcaseBusiness:x==='environmental'||x==='planning'?Factory:x==='legal'||x==='competition'?Scale:x==='municipal'||x==='authority'?FileText:Radar;}
function deltaTheme(x:StrategicDelta['theme']){return x==='contracts'?'Kontrakt/upphandling':x==='capacity'?'Kapacitet/anläggning':x==='permits'?'Tillstånd/miljö':x==='planning'?'Mark/planering':x==='m-and-a'?'Förvärv/M&A':x==='investment'?'Investering':x==='pricing'?'Pris/materialflöden':x==='jobs'?'Rekrytering':x==='legal'?'Juridik/reglering':'Övrigt';}
function deltaLabel(x:StrategicDelta['direction']){return x==='surging'?'Accelererar tydligt':x==='new-pattern'?'Nytt observerat mönster':x==='rising'?'Ökar':x==='falling'?'Lägre observerad aktivitet':'Stabil';}
function jobSignalLabel(x:JobSignal['classification']){return x.signalStrength==='high'?'stark signal':x.signalStrength==='medium'?'medel signal':x.signalStrength==='low'?'svag signal':'okänd signalstyrka';}

export default function CompetitorNow({actors}:{actors:string[]}){
  const actorKey=useMemo(()=>actors.join(','),[actors]);
  const [data,setData]=useState<Payload|null>(null);
  const [selected,setSelected]=useState(actors[0]??'');
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState<string|null>(null);

  const load=async()=>{
    setLoading(true);setError(null);
    try{
      const r=await fetch('/api/industry-feed?industry=waste&days=30',{cache:'no-store'});
      if(!r.ok)throw new Error(`HTTP ${r.status}`);
      setData(await r.json() as Payload);
    }catch(e){setError(e instanceof Error?e.message:'Kunde inte hämta aktuella konkurrentssignaler')}
    finally{setLoading(false)}
  };
  useEffect(()=>{setSelected(prev=>actors.includes(prev)?prev:(actors[0]??''));void load()},[actorKey]);

  const cards=useMemo(()=>actors.map(actor=>{
    const timelines=(data?.signalTimelines??[]).filter(t=>t.competitors.some(c=>actorMatches(c,actor))).sort((a,b)=>b.escalationScore-a.escalationScore);
    const jobs=(data?.competitorJobSignals??[]).filter(j=>actorMatches(j.competitor,actor));
    const websiteChanges=(data?.competitorWebsiteMonitor?.changes??[]).filter(w=>actorMatches(w.competitor,actor));
    const entityView=(data?.competitorEntityViews??[]).find(v=>actorMatches(v.organization,actor));
    const deltas=(data?.strategicDeltas??[]).filter(d=>actorMatches(d.competitor,actor));
    const drilldowns=(data?.evidenceDrilldowns??[]).filter(d=>actorMatches(d.competitor,actor));
    const discovery=(data?.discoveryResults??[]).filter(d=>d.competitors?.some(c=>actorMatches(c,actor))).sort((a,b)=>b.score-a.score);
    const classes=[...new Set(timelines.flatMap(t=>t.sourceClasses))];
    return {actor,timelines,jobs,websiteChanges,entityView,deltas,drilldowns,discovery,classes,score:timelines.reduce((n,t)=>n+t.escalationScore,0)+jobs.length*12+websiteChanges.reduce((n,w)=>n+(w.importance==='high'?25:w.importance==='medium'?14:5),0)+discovery.length*3,escalating:timelines.filter(t=>t.direction==='escalating').length};
  }).sort((a,b)=>b.score-a.score),[actors,data]);
  const current=cards.find(c=>c.actor===selected)??cards[0];

  return <section className="competitorNow">
    <div className="competitorNowHead"><div><p className="eyebrow"><Radar size={13}/> KONKURRENTKORT · NU</p><h2>Vad verkar konkurrenterna göra just nu?</h2><p>Aktuella jobbannonser, formella processer och sammansatta signaler samlas per aktör. Enskilda träffar hålls isär från Bevaklys tolkning.</p></div><button className="iconButton" onClick={()=>void load()} aria-label="Uppdatera aktuella konkurrentssignaler"><RefreshCw size={17} className={loading?'spin':''}/></button></div>
    {error&&<div className="emptyState">Aktuella signaler kunde inte hämtas: {error}</div>}
    <div className="competitorNowTabs">{cards.map(card=><button key={card.actor} onClick={()=>setSelected(card.actor)} className={card.actor===current?.actor?'active':''}><strong>{card.actor}</strong><span>{card.timelines.length} signaler · {card.jobs.length} jobb</span></button>)}</div>
    {current&&<div className="competitorNowCard">
      <div className="competitorNowHero"><div><div className="competitorNowName"><Building2 size={20}/><h3>{current.actor}</h3></div><p>{current.timelines.length?current.timelines[0].headline:'Ingen robust sammansatt förändringssignal just nu.'}</p></div><div className="competitorNowScore"><strong>{current.timelines[0]?.escalationScore??0}</strong><span>starkaste signal</span></div></div>
      <div className="competitorNowStats">
        <div><Radar size={15}/><strong>{current.timelines.length}</strong><span>aktiva förändringssignaler</span></div>
        <div><TrendingUp size={15}/><strong>{current.escalating}</strong><span>signaler som stärks</span></div>
        <div><BriefcaseBusiness size={15}/><strong>{current.jobs.length}</strong><span>jobbannonser</span></div>
        <div><FileText size={15}/><strong>{current.websiteChanges.length}</strong><span>webbändringar</span></div>
      </div>
      {current.websiteChanges.length>0&&<section className="competitorChangeProfile"><div className="competitorChangeProfileHead"><div><span>WEBBÄNDRINGAR · 2.0</span><strong>Vad ändrades på konkurrentens egen webb?</strong></div><small>Före/efter · observerad text</small></div><div className="competitorDeltaGrid">{current.websiteChanges.slice(0,4).map(w=><article key={w.id}><div className="competitorDeltaTop"><span>{w.pageType==='careers'?'Karriärsida':'Webbplats'}</span><b>{w.importance==='high'?'Granska':'Observerad ändring'}</b></div><strong>{w.dimensions?.length?w.dimensions.join(' · '):'Ingen strategisk dimension verifierad'}</strong><p>{w.assessment??w.summary}</p>{w.addedSnippets?.length?<details className="evidenceDrilldown"><summary><span>Visa före/efter</span><small>{w.addedSnippets.length} tillagt · {w.removedSnippets?.length??0} borttaget</small></summary><div className="evidenceDrilldownBody"><div className="evidenceSection"><span>TILLAGT</span>{w.addedSnippets.map((x,i)=><p key={i}>+ {x}</p>)}</div>{w.removedSnippets?.length?<div className="evidenceSection gaps"><span>BORTTAGET</span>{w.removedSnippets.map((x,i)=><p key={i}>− {x}</p>)}</div>:null}<div className="evidenceSection assessment"><span>GUARDRAIL</span><p>{w.guardrail}</p></div><a href={w.url} target="_blank" rel="noreferrer">Öppna aktuell sida <ExternalLink size={12}/></a></div></details>:null}</article>)}</div></section>}
      <section className="competitorChangeProfile">
        <div className="competitorChangeProfileHead"><div><span>LEVANDE FÖRÄNDRINGSPROFIL</span><strong>Vad har faktiskt förändrats?</strong></div><small>{data?.strategicDeltaSummary?.historyVerified?'Historik verifierad från databas':'Begränsad historik – aktuell körning'}</small></div>
        {current.deltas.length>0?<div className="competitorDeltaGrid">{current.deltas.slice(0,6).map(delta=>{const drill=current.drilldowns.find(d=>d.theme===delta.theme);return <article key={`${delta.competitor}-${delta.theme}`}><div className="competitorDeltaTop"><span>{deltaTheme(delta.theme)}</span><b>{deltaLabel(delta.direction)}</b></div><strong>{delta.recentSignals} case senaste 30d <em>mot {delta.baselineSignals} i 90d-baslinjen</em></strong><p>{delta.reasons[0]??'Observerad aktivitet avviker från konkurrentens egen baslinje.'}</p><small>Säkerhet i mätningen: {delta.confidence==='high'?'hög':delta.confidence==='medium'?'medel':'låg'} · {new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short'}).format(new Date(delta.latestObservedAt))}</small>{drill&&<details className="evidenceDrilldown"><summary>Visa evidens och resonemang</summary><div className="evidenceDrilldownBody"><div className="evidenceClaim"><span>PÅSTÅENDE</span><strong>{drill.claim}</strong></div><div className="evidenceSection"><span>FAKTA · ORIGINALKÄLLOR</span>{drill.observedFacts.length?drill.observedFacts.map((f,i)=><a key={`${f.url}-${i}`} href={f.url} target="_blank" rel="noreferrer"><div><strong>{f.title}</strong><small>{f.source} · {new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short',year:'numeric'}).format(new Date(f.publishedAt))}</small></div><ExternalLink size={12}/></a>):<p>Ingen öppningsbar originalkälla finns i den aktuella körningens tidslinjer för detta historiska delta.</p>}</div><div className="evidenceSection"><span>VARFÖR BEVAKLY KOPPLAR IHOP DET</span>{drill.linkLogic.map((x,i)=><p key={i}>{x}</p>)}</div>{drill.assessment.length>0&&<div className="evidenceSection assessment"><span>BEVAKLY BEDÖMER</span>{drill.assessment.map((x,i)=><p key={i}>{x}</p>)}</div>}<div className="evidenceSection gaps"><span>VAD SAKNAS FORTFARANDE?</span>{drill.missingEvidence.length?drill.missingEvidence.map((x,i)=><p key={i}>{x}</p>):<p>Ingen särskild evidenslucka identifierades i detta drill-down. Det betyder inte att analysen är fullständig.</p>}</div><div className="evidenceCoverage"><span>{drill.evidenceCoverage.linkedCases}/{drill.evidenceCoverage.currentCases} case länkade</span><span>{drill.evidenceCoverage.sourceCount} öppningsbara källor</span></div></div></details>}</article>})}</div>:<div className="competitorDeltaEmpty"><strong>Ingen tydlig aktivitetsförändring mot baslinjen.</strong><span>Det är också ett resultat. Bevakly fyller inte profilen med förändringar när underlaget inte visar någon.</span></div>}
        <div className="competitorChangeProfileGuard"><strong>FAKTA ≠ BEDÖMNING</strong><span>Profilen beskriver förändring i Bevaklys observerade underlag. Den bevisar inte att {current.actor} har ändrat strategi. Öppna signalerna nedan för källor och evidens.</span></div>
      </section>
      {current.classes.length>0&&<div className="competitorNowSources">{current.classes.map(cls=>{const Icon=sourceIcon(cls);return <span key={cls}><Icon size={12}/>{sourceLabel(cls)}</span>})}</div>}
      {current.timelines.length>0?<div className="competitorSignalList">{current.timelines.slice(0,4).map((signal,i)=><details key={signal.id} open={i===0}>
        <summary><div><span className={`changeDirection change-${signal.direction}`}>{signal.direction==='escalating'?'Stärks':signal.direction==='cooling'?'Kyls ned':'Stabil'}</span><h4>{signal.headline}</h4><small>{stageLabel(signal.stage)} · {signal.facts} fakta · {signal.escalationScore}/100 · Tolkning {signal.interpretationConfidence}</small></div><ExternalLink size={15}/></summary>
        <div className="competitorSignalBody"><div className="changeTimeline">{signal.milestones.map((m,mi)=><a key={`${m.url}-${mi}`} href={m.url} target="_blank" rel="noreferrer"><time>{new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short'}).format(new Date(m.publishedAt))}</time><span><strong>{m.title}</strong><small>{m.source} · {sourceLabel(m.sourceClass)}</small></span><ExternalLink size={11}/></a>)}</div><p><strong>Bevaka nästa:</strong> {signal.watchNext.slice(0,3).join(' · ')}</p></div>
      </details>)}</div>:<div className="competitorNowEmpty"><strong>Ingen sammansatt förändringssignal ännu.</strong><span>Det betyder inte att konkurrenten är inaktiv. Bevakly saknar just nu tillräckligt oberoende stöd för att kalla träffarna en sammanhängande förändring.</span></div>}
      {current.entityView&&<section className="competitorRelations"><div className="competitorJobsHead"><Building2 size={15}/><strong>Observerade relationer</strong><span>{current.entityView.geographies.length+current.entityView.signalClasses.length}</span></div><div className="competitorRelationGrid"><div><small>Geografier</small>{current.entityView.geographies.slice(0,6).map(x=><span key={x.label}><strong>{x.label}</strong><em>{x.observations} observationer</em></span>)}</div><div><small>Signaltyper</small>{current.entityView.signalClasses.slice(0,6).map(x=><span key={x.label}><strong>{sourceLabel(x.label)}</strong><em>{x.observations} observationer</em></span>)}</div><div><small>Källor</small>{current.entityView.sources.slice(0,6).map(x=><span key={x.label}><strong>{x.label}</strong><em>{x.observations} observationer</em></span>)}</div></div><p className="relationCaveat">Relationerna betyder att aktören och platsen/signaltypen förekommer tillsammans i samma källunderlag. Bevakly gissar inte ägande, dotterbolag eller anläggningsrelationer.</p></section>}
      {current.websiteChanges.length>0&&<section className="competitorWebChanges"><div className="competitorJobsHead"><Radar size={15}/><strong>Webbplatsförändringar</strong><span>{current.websiteChanges.length}</span></div>{current.websiteChanges.slice(0,5).map(change=><a key={change.id} href={change.url} target="_blank" rel="noreferrer"><div><strong>{change.pageType==='careers'?'Karriärsidan ändrades':'Webbplatsen ändrades'}</strong><small>{change.importance} betydelse · förändringsgrad {Math.round(change.changeRatio*100)}%{change.addedTerms.length?` · nya termer: ${change.addedTerms.join(', ')}`:''}</small><p>{change.summary}</p></div><ExternalLink size={12}/></a>)}</section>}
      {current.jobs.length>0&&<section className="competitorJobs"><div className="competitorJobsHead"><BriefcaseBusiness size={15}/><strong>Rekryteringssignaler</strong><span>{current.jobs.length}</span></div>{current.jobs.slice(0,5).map(job=><a key={job.id} href={job.url} target="_blank" rel="noreferrer"><div><strong>{job.title}</strong><small>{job.geographies.join(', ')||'Geografi saknas'} · {jobSignalLabel(job.classification)}</small></div><ExternalLink size={12}/></a>)}</section>}
      <p className="actorDisclaimer">Konkurrentkortet visar aktuell discovery från denna körning. Jobbvolym eller en ensam offentlig handling räcker aldrig ensam för att Bevakly ska påstå en strategisk förflyttning.</p>
    </div>}
  </section>;
}
