"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, GitBranch, RefreshCw, ShieldAlert, Telescope } from "lucide-react";

type Move={id:string;actor:string;kind:string;label:string;hypothesis:string;confidence:'hög'|'medel'|'låg';score:number;evidenceCount:number;independentSources:number;evidenceDomains:string[];categories:string[];geographies:string[];firstSeen:string|null;lastSeen:string|null;evidence:{id:string;title:string;category:string|null;geography:string|null;publishedAt:string|null;sourceDomain:string|null;relevanceScore:number|null}[];supportingSignals:string[];counterEvidence:string[];watchNext:string[];caveat:string};
type Payload={historyEnabled:boolean;reason:string|null;eventCount:number;moves:Move[];disclaimer:string};
function date(v:string|null){if(!v)return 'okänt datum';return new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short'}).format(new Date(v))}
export default function StrategicMoves({actors}:{actors:string[]}){
  const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(false);const [openId,setOpenId]=useState<string|null>(null);
  const key=actors.join(',');
  const load=async()=>{setLoading(true);try{const qs=new URLSearchParams();if(key)qs.set('actors',key);const r=await fetch(`/api/strategic-moves?${qs}`,{cache:'no-store'});setData(await r.json() as Payload)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[key]);
  return <section className="strategicMoves"><div className="strategicMovesHead"><div><p className="eyebrow"><GitBranch size={13}/> STRATEGIC MOVES · v2.1</p><h2>Vilka större rörelser kan vara på väg?</h2><p>Bevakly kopplar ihop separata signaler till testbara hypoteser — och visar samtidigt vad som talar emot dem.</p></div><button className="iconButton" onClick={()=>void load()} aria-label="Uppdatera Strategic Moves"><RefreshCw size={17} className={loading?'spin':''}/></button></div>
  {!data?.historyEnabled&&!loading&&<div className="emptyState">Historik krävs för Strategic Moves. {data?.reason}</div>}
  {data?.historyEnabled&&!loading&&data.moves.length===0&&<div className="emptyState">Inga tillräckligt sammansatta rörelser kan beläggas ännu. Bevakly väntar hellre på flera olika signaltyper än skapar en hypotes från en enstaka nyhet.</div>}
  {data?.moves?.length>0&&<div className="moveList">{data.moves.map(m=><article key={m.id} className="moveCard"><div className="moveTop"><div><span className="moveActor">{m.actor}</span><span className={`moveConfidence ${m.confidence}`}>{m.confidence} säkerhet</span></div><strong>{m.score}/100</strong></div><h3>{m.label}</h3><p className="moveHypothesis"><b>BEVAKLY HYPOTES</b>{m.hypothesis}</p><div className="moveMetrics"><span><b>{m.evidenceCount}</b> signaler</span><span><b>{m.independentSources}</b> källdomäner</span><span><b>{m.categories.length}</b> teman</span><span><b>{m.geographies.length}</b> geografier</span></div><div className="moveTags">{m.categories.slice(0,5).map(x=><span key={x}>{x}</span>)}</div><button className="moveExpand" onClick={()=>setOpenId(openId===m.id?null:m.id)}>{openId===m.id?'Dölj underlag':'Visa stöd & motbevis'} <ArrowUpRight size={13}/></button>
  {openId===m.id&&<div className="moveDetails"><section><small className="sectionKicker">STÖDJER HYPOTESEN</small>{m.supportingSignals.map(x=><p key={x}>• {x}</p>)}<div className="moveEvidence">{m.evidence.map(e=><div key={e.id}><time>{date(e.publishedAt)}</time><div><strong>{e.title}</strong><span>{e.category??'Övrigt'} · {e.sourceDomain??'okänd källa'}</span></div></div>)}</div></section><section className="counterBox"><small className="sectionKicker">VAD TALAR EMOT?</small>{m.counterEvidence.map(x=><p key={x}>• {x}</p>)}</section><section><small className="sectionKicker"><Telescope size={12}/> BEVAKA HÄRNÄST</small>{m.watchNext.map(x=><p key={x}>• {x}</p>)}</section><div className="moveWarning"><ShieldAlert size={15}/><span>{m.caveat}</span></div></div>}</article>)}</div>}
  {data&&<p className="actorDisclaimer">{data.disclaimer}</p>}</section>
}
