'use client';
import {useEffect,useMemo,useState} from 'react';
import {Eye,Plus,ExternalLink} from 'lucide-react';
import {assessWatchQuestion,createWatchQuestion,type WatchQuestion,type WatchQuestionTimeline} from '@/lib/intelligence/watch-questions';
export default function WatchQuestions({profileId,timelines}:{profileId:string;timelines:WatchQuestionTimeline[]}){
 const key=`bevakly:watch-questions:v1:${profileId}`;const [items,setItems]=useState<WatchQuestion[]>([]);const [text,setText]=useState('');const [ready,setReady]=useState(false);
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(key)||'[]'))}catch{setItems([])}finally{setReady(true)}},[key]);
 useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(items.slice(-50)))},[items,key,ready]);
 const active=useMemo(()=>items.filter(x=>x.status==='active').map(q=>({q,a:assessWatchQuestion(q,timelines)})),[items,timelines]);
 const add=()=>{const q=text.trim();if(!q)return;const next=createWatchQuestion(q);setItems(p=>p.some(x=>x.id===next.id)?p:[...p,next]);setText('')};
 return <section className="watchQuestions"><div className="watchQuestionsHead"><div><p className="eyebrow"><Eye size={14}/> BEVAKNINGSFRÅGOR</p><h3>Följ en fråga – inte bara ett sökord</h3><p>Bevakly samlar signaler som kan stärka, försvaga eller lämna frågan obesvarad.</p></div></div><div className="watchQuestionInput"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add()}} placeholder="Exempel: Ökar PreZero sin behandlingskapacitet i Mellansverige?"/><button onClick={add}><Plus size={14}/> Följ frågan</button></div>{active.length>0&&<div className="watchQuestionList">{active.map(({q,a})=><article key={q.id}><div className="watchQuestionTop"><span>{a.state==='strengthening'?'STÄRKS':a.state==='mixed'?'BLANDAD':a.state==='cooling'?'SVALNAR':'OTILLRÄCKLIGT UNDERLAG'}</span><button onClick={()=>setItems(p=>p.map(x=>x.id===q.id?{...x,status:'closed'}:x))}>Avsluta</button></div><h4>{q.question}</h4><p>{a.summary}</p>{a.supporting.length>0&&<details><summary>Visa stödjande evidens ({a.supporting.length})</summary><div className="watchQuestionEvidence">{a.supporting.slice(0,5).flatMap(x=>x.milestones.slice(-1)).map((m,i)=><a key={`${m.url}-${i}`} href={m.url} target="_blank" rel="noreferrer"><span>{m.title}<small>{m.source}</small></span><ExternalLink size={11}/></a>)}</div></details>}<div className="watchQuestionMissing">{a.missing.slice(0,3).map((x,i)=><small key={i}>• {x}</small>)}</div><small className="watchQuestionGuard">{a.guardrail}</small></article>)}</div>}<small className="storyClusterNote">Bevakningsfrågorna sparas lokalt i webbläsaren i v2.94. De ändrar inte signalernas confidence eller skapar fakta.</small></section>;
}
