export type SourceType = "authority" | "industry" | "media" | "research" | "eu" | "competitor" | "company" | "procurement";
export type SourceScope = "sweden" | "nordic" | "eu" | "international";
export type SourceTier = 1 | 2 | 3;

export type WatchSource = {
  id: string;
  name: string;
  listingUrl: string;
  baseUrl: string;
  type: SourceType;
  scope: SourceScope;
  tier: SourceTier;
  trustScore: number;
  enabled: boolean;
  competitorName?: string;
  description?: string;
  regions?: string[];
  publisherGroup?: string;
};

export const wasteSources: WatchSource[] = [
  { id:"naturvardsverket-news", name:"Naturvårdsverket", listingUrl:"https://www.naturvardsverket.se/om-oss/aktuellt/nyheter-och-pressmeddelanden/", baseUrl:"https://www.naturvardsverket.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Svensk miljömyndighet: regler, vägledning och tillsyn." },
  { id:"naturvardsverket-waste", name:"Naturvårdsverket – Avfall", listingUrl:"https://www.naturvardsverket.se/avfall", baseUrl:"https://www.naturvardsverket.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Ämnessidor och förändringar inom svensk avfallspolitik." },
  { id:"regeringen-press", name:"Regeringen", listingUrl:"https://www.regeringen.se/pressmeddelanden/", baseUrl:"https://www.regeringen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Regeringsbeslut, utredningar och politiska förändringar." },
  { id:"riksdagen-documents", name:"Sveriges riksdag", listingUrl:"https://www.riksdagen.se/sv/dokument-och-lagar/", baseUrl:"https://www.riksdagen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Propositioner, betänkanden, lagar och riksdagsdokument." },
  { id:"avfall-sverige", name:"Avfall Sverige", listingUrl:"https://www.avfallsverige.se/aktuellt/nyheter/", baseUrl:"https://www.avfallsverige.se", type:"industry", scope:"sweden", tier:1, trustScore:94, enabled:true, description:"Kommunernas branschorganisation inom avfallshantering." },
  { id:"recyclingnet", name:"Recycling", listingUrl:"https://www.recyclingnet.se/", baseUrl:"https://www.recyclingnet.se", type:"media", scope:"sweden", tier:2, trustScore:86, enabled:true, description:"Svenskt branschmedium för återvinning och avfall." },
  { id:"rise-circular", name:"RISE", listingUrl:"https://www.ri.se/sv/nyheter", baseUrl:"https://www.ri.se", type:"research", scope:"sweden", tier:2, trustScore:91, enabled:true, description:"Forskning, pilotprojekt och teknik inom cirkulär omställning." },
  { id:"energimyndigheten-news", name:"Energimyndigheten", listingUrl:"https://www.energimyndigheten.se/nyhetsarkiv/", baseUrl:"https://www.energimyndigheten.se", type:"authority", scope:"sweden", tier:1, trustScore:98, enabled:true, description:"Energiåtervinning, avfallspriser, industristöd, CCS och investeringar i omställningen." },
  { id:"scb-waste", name:"SCB – Avfallsstatistik", listingUrl:"https://www.scb.se/hitta-statistik/statistik-efter-amne/miljo/avfall/avfall-uppkommet-och-behandlat/", baseUrl:"https://www.scb.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Officiell statistik om uppkommet och behandlat avfall i Sverige." },
  { id:"svenskt-vatten", name:"Svenskt Vatten", listingUrl:"https://www.svensktvatten.se/aktuellt/nyheter/", baseUrl:"https://www.svensktvatten.se", type:"industry", scope:"sweden", tier:2, trustScore:90, enabled:true, description:"VA, slam, resursåtervinning, Revaq och cirkulära flöden." },
  { id:"avfall-sverige-newsletter", name:"Avfall Sverige – Nyhetsbrev", listingUrl:"https://www.avfallsverige.se/aktuellt/nyhetsbrev/", baseUrl:"https://www.avfallsverige.se", type:"industry", scope:"sweden", tier:2, trustScore:91, enabled:true, description:"Tematiska sammanställningar som kan fånga PFAS, energiåtervinning, återbruk och marknadsförändringar." },
  { id:"eu-environment", name:"EU-kommissionen – Environment", listingUrl:"https://environment.ec.europa.eu/news_en", baseUrl:"https://environment.ec.europa.eu", type:"eu", scope:"eu", tier:1, trustScore:100, enabled:true, description:"EU-regler, policy och nyheter inom miljö, avfall och cirkulär ekonomi." },
  { id:"eu-circular", name:"EU-kommissionen – Circular Economy", listingUrl:"https://environment.ec.europa.eu/strategy/circular-economy_en", baseUrl:"https://environment.ec.europa.eu", type:"eu", scope:"eu", tier:1, trustScore:100, enabled:true, description:"Cirkulär ekonomi, sekundära råvaror och kommande EU-policy." },
  { id:"eea-news", name:"European Environment Agency", listingUrl:"https://www.eea.europa.eu/en/newsroom/news", baseUrl:"https://www.eea.europa.eu", type:"eu", scope:"eu", tier:1, trustScore:98, enabled:true, description:"Europeisk miljödata, analyser och cirkulär ekonomi." },
  { id:"cinea-news", name:"CINEA / LIFE", listingUrl:"https://cinea.ec.europa.eu/news-events/news_en", baseUrl:"https://cinea.ec.europa.eu", type:"eu", scope:"eu", tier:2, trustScore:96, enabled:true, description:"EU-finansierade innovations- och demonstrationsprojekt." },
  { id:"letsrecycle", name:"letsrecycle.com", listingUrl:"https://www.letsrecycle.com/news/category/international/", baseUrl:"https://www.letsrecycle.com", type:"media", scope:"international", tier:3, trustScore:78, enabled:true, description:"Internationella återvinnings- och avfallsnyheter med europeisk relevans." },

  // Lokala myndighetssignaler. Länsstyrelsernas nyhetsflöden kan fånga miljöprövning och kapacitetsförändringar innan de blir breda branschnyheter.
  { id:"lansstyrelsen-orebro", name:"Länsstyrelsen Örebro", listingUrl:"https://www.lansstyrelsen.se/orebro/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Miljöprövning, kungörelser, tillstånd och lokala verksamhetsförändringar i Örebro/Värmlands prövningsområde." },
  { id:"lansstyrelsen-vastmanland", name:"Länsstyrelsen Västmanland", listingUrl:"https://www.lansstyrelsen.se/vastmanland/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Miljöprövning, avfallsverksamhet och lokala beslut i Västmanlands län." },

  // Sveriges tolv miljöprövningsdelegationer (MPD). Dessa länsstyrelser prövar miljöfarliga B-verksamheter i samtliga län.
  { id:"lansstyrelsen-skane-mpd", name:"Länsstyrelsen Skåne", listingUrl:"https://www.lansstyrelsen.se/skane/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Skåne och Blekinge: tillstånd, ändringstillstånd och kungörelser om miljöfarlig verksamhet." },
  { id:"lansstyrelsen-dalarna-mpd", name:"Länsstyrelsen Dalarna", listingUrl:"https://www.lansstyrelsen.se/dalarna/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Dalarna och Gävleborg: miljöprövning, deponi, avfallsanläggningar och kapacitetsförändringar." },
  { id:"lansstyrelsen-stockholm-mpd", name:"Länsstyrelsen Stockholm", listingUrl:"https://www.lansstyrelsen.se/stockholm/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Stockholm och Gotland: tillstånd och förändringar i miljöfarlig verksamhet." },
  { id:"lansstyrelsen-ostergotland-mpd", name:"Länsstyrelsen Östergötland", listingUrl:"https://www.lansstyrelsen.se/ostergotland/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Östergötland och Jönköping: bland annat utökade avfallsanläggningar och miljötillstånd." },
  { id:"lansstyrelsen-uppsala-mpd", name:"Länsstyrelsen Uppsala", listingUrl:"https://www.lansstyrelsen.se/uppsala/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Uppsala, Västmanland och Södermanland: tillstånd och ändringar för miljöfarlig verksamhet." },
  { id:"lansstyrelsen-kalmar-mpd", name:"Länsstyrelsen Kalmar", listingUrl:"https://www.lansstyrelsen.se/kalmar/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Kalmar och Kronoberg: tillstånd, kungörelser och miljöprövning." },
  { id:"lansstyrelsen-vasternorrland-mpd", name:"Länsstyrelsen Västernorrland", listingUrl:"https://www.lansstyrelsen.se/vasternorrland/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Västernorrland och Jämtland: miljötillstånd, industri- och avfallsverksamhet." },
  { id:"lansstyrelsen-vasterbotten-mpd", name:"Länsstyrelsen Västerbotten", listingUrl:"https://www.lansstyrelsen.se/vasterbotten/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Västerbotten: miljöprövning, industri, etableringar och tillstånd." },
  { id:"lansstyrelsen-norrbotten-mpd", name:"Länsstyrelsen Norrbotten", listingUrl:"https://www.lansstyrelsen.se/norrbotten/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Norrbotten: miljöprövning, industriella etableringar och avfallsrelaterade tillstånd." },
  { id:"lansstyrelsen-halland-mpd", name:"Länsstyrelsen Halland", listingUrl:"https://www.lansstyrelsen.se/halland/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Halland: tillstånd och ändringar för miljöfarlig verksamhet." },
  { id:"lansstyrelsen-vastra-gotaland-mpd", name:"Länsstyrelsen Västra Götaland", listingUrl:"https://www.lansstyrelsen.se/vastra-gotaland/om-oss/nyheter-och-press.html", baseUrl:"https://www.lansstyrelsen.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"MPD för Västra Götaland: omfattande miljöprövning av industri, återvinning och avfallsverksamhet." },

  // Lokala/regionala redaktioner. Breda startsidor filtreras hårt på avfalls- och etableringsord innan en artikel hämtas.
  { id:"svt-orebro", name:"SVT Nyheter Örebro", listingUrl:"https://www.svt.se/nyheter/lokalt/orebro/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Örebro"], publisherGroup:"svt-local", description:"Lokala signaler om avfall, återvinning, anläggningar, miljötillstånd och kommunala förändringar i Örebro län." },
  { id:"svt-vastmanland", name:"SVT Nyheter Västmanland", listingUrl:"https://www.svt.se/nyheter/lokalt/vastmanland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Västmanland"], publisherGroup:"svt-local", description:"Lokala marknads- och anläggningssignaler i Västmanland." },
  { id:"svt-dalarna", name:"SVT Nyheter Dalarna", listingUrl:"https://www.svt.se/nyheter/lokalt/dalarna/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Dalarna"], publisherGroup:"svt-local", description:"Lokala signaler från Dalarna, inklusive kommunal avfallshantering och etableringar." },
  { id:"svt-stockholm", name:"SVT Nyheter Stockholm", listingUrl:"https://www.svt.se/nyheter/lokalt/stockholm/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Stockholm"], publisherGroup:"svt-local", description:"Lokala marknads-, miljö- och avfallssignaler i Stockholmsområdet." },
  { id:"svt-ost", name:"SVT Nyheter Öst", listingUrl:"https://www.svt.se/nyheter/lokalt/ost/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Östergötland","Gotland"], publisherGroup:"svt-local", description:"Lokala signaler från Östergötland och Gotland." },
  { id:"svt-vast", name:"SVT Nyheter Väst", listingUrl:"https://www.svt.se/nyheter/lokalt/vast/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Västra Götaland"], publisherGroup:"svt-local", description:"Lokala signaler från Västsverige och Göteborgsområdet." },
  { id:"svt-skane", name:"SVT Nyheter Skåne", listingUrl:"https://www.svt.se/nyheter/lokalt/skane/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Skåne"], publisherGroup:"svt-local", description:"Lokala marknads-, avfalls- och miljösignaler i Skåne." },
  { id:"svt-norrbotten", name:"SVT Nyheter Norrbotten", listingUrl:"https://www.svt.se/nyheter/lokalt/norrbotten/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Norrbotten"], publisherGroup:"svt-local", description:"Lokala industri-, etablerings- och återvinningssignaler i Norrbotten." },
  { id:"svt-vasterbotten", name:"SVT Nyheter Västerbotten", listingUrl:"https://www.svt.se/nyheter/lokalt/vasterbotten/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Västerbotten"], publisherGroup:"svt-local", description:"Lokala industri-, etablerings- och återvinningssignaler i Västerbotten." },
  { id:"svt-vasternorrland", name:"SVT Nyheter Västernorrland", listingUrl:"https://www.svt.se/nyheter/lokalt/vasternorrland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Västernorrland"], publisherGroup:"svt-local", description:"Lokala signaler om kommunal avfallshantering, teknik och investeringar i Västernorrland." },
  { id:"svt-gavleborg", name:"SVT Nyheter Gävleborg", listingUrl:"https://www.svt.se/nyheter/lokalt/gavleborg/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Gävleborg"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, miljö, kommunala beslut, anläggningar och företag i Gävleborg." },
  { id:"svt-jamtland", name:"SVT Nyheter Jämtland", listingUrl:"https://www.svt.se/nyheter/lokalt/jamtland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Jämtland"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, miljö, upphandling och kapacitet i Jämtland." },
  { id:"svt-uppsala", name:"SVT Nyheter Uppsala", listingUrl:"https://www.svt.se/nyheter/lokalt/uppsala/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Uppsala"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, miljötillstånd, kommunala beslut och marknadsförändringar i Uppsala län." },
  { id:"svt-varmland", name:"SVT Nyheter Värmland", listingUrl:"https://www.svt.se/nyheter/lokalt/varmland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Värmland"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, transporter, behandling, upphandling och anläggningar i Värmland." },
  { id:"svt-sormland", name:"SVT Nyheter Sörmland", listingUrl:"https://www.svt.se/nyheter/lokalt/sormland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Södermanland"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, återvinning, kommunala avtal och industriella förändringar i Södermanland." },
  { id:"svt-blekinge", name:"SVT Nyheter Blekinge", listingUrl:"https://www.svt.se/nyheter/lokalt/blekinge/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Blekinge"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, miljö, hamn-/industriflöden och kommunala beslut i Blekinge." },
  { id:"svt-halland", name:"SVT Nyheter Halland", listingUrl:"https://www.svt.se/nyheter/lokalt/halland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Halland"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, miljöprövning, upphandling och anläggningsförändringar i Halland." },
  { id:"svt-jonkoping", name:"SVT Nyheter Jönköping", listingUrl:"https://www.svt.se/nyheter/lokalt/jonkoping/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Jönköping"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler om avfall, återvinning, kommunal service och investeringar i Jönköpings län." },
  { id:"svt-smaland", name:"SVT Nyheter Småland", listingUrl:"https://www.svt.se/nyheter/lokalt/smaland/", baseUrl:"https://www.svt.se", type:"media", scope:"sweden", tier:3, trustScore:88, enabled:true, regions:["Kalmar","Kronoberg"], publisherGroup:"svt-local", description:"Lokala journalistiska signaler från Kalmar och Kronoberg om avfall, återvinning, miljö och kommunala marknadsförändringar." },

  // Fler verifierade svenska bransch- och regionala källor. Dessa ökar nyhetsbredden utan att behandla bolagens egna publiceringar som oberoende bekräftelse.
  { id:"sysav-news", name:"Sysav", listingUrl:"https://www.sysav.se/", baseUrl:"https://www.sysav.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, description:"Sydsvensk avfallsaktör: anläggningar, behandling, återvinning, investeringar och driftförändringar." },
  { id:"stockholm-vatten-avfall", name:"Stockholm Vatten och Avfall", listingUrl:"https://stockholmvatten.mynewsdesk.com/latest_news", baseUrl:"https://stockholmvatten.mynewsdesk.com", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, description:"Stockholms avfalls- och återvinningsnyheter, teknikprojekt, anläggningar och förändringar." },
  { id:"vakin-news", name:"Vakin", listingUrl:"https://www.mynewsdesk.com/se/vakin/latest_news", baseUrl:"https://www.mynewsdesk.com", type:"company", scope:"sweden", tier:2, trustScore:84, enabled:true, description:"Regionala avfalls- och återvinningssignaler från Umeåregionen." },
  { id:"nacka-vatten-avfall", name:"Nacka vatten och avfall", listingUrl:"https://www.mynewsdesk.com/se/nacka-vatten-och-avfall-ab/latest_news", baseUrl:"https://www.mynewsdesk.com", type:"company", scope:"sweden", tier:2, trustScore:84, enabled:true, description:"Kommunala avfalls-, återbruks- och kretsloppsförändringar i Nacka." },
  { id:"uddevalla-energi-recycling", name:"Uddevalla Energi", listingUrl:"https://www.mynewsdesk.com/se/uddevalla-energi-ab/subjects/miljoeteknik-aatervinning", baseUrl:"https://www.mynewsdesk.com", type:"company", scope:"sweden", tier:2, trustScore:82, enabled:true, description:"Regionala återvinnings-, återbruks- och avfallsnyheter i Västsverige." },
  { id:"ohlssons-news", name:"Ohlssons", listingUrl:"https://www.ohlssons.se/nyheter/", baseUrl:"https://www.ohlssons.se", type:"competitor", scope:"sweden", tier:2, trustScore:82, enabled:true, competitorName:"Ohlssons", description:"Bolagets egna nyheter om kommunala uppdrag, investeringar, fordon, expansion och återvinning." },
  { id:"verdis-news", name:"Verdis", listingUrl:"https://www.verdis.se/nyheter/", baseUrl:"https://www.verdis.se", type:"competitor", scope:"sweden", tier:2, trustScore:82, enabled:true, competitorName:"Verdis", description:"Bolagets egna nyheter om insamling, elektrifiering, uppdrag och expansion." },

  // Regionala avfallsaktörer: egna källor används som fakta om den egna verksamheten, inte som oberoende mediebekräftelse.
  { id:"vafab-news", name:"Vafabmiljö", listingUrl:"https://www.mynewsdesk.com/se/vafab-miljoe-ab/latest_news", baseUrl:"https://www.mynewsdesk.com", type:"company", scope:"sweden", tier:2, trustScore:84, enabled:true, description:"Regionala investeringar, återbruk, anläggningar och förändringar i Västmanland, Heby och Enköping." },
  { id:"renova-recycling", name:"Renova", listingUrl:"https://www.mynewsdesk.com/se/renova/subjects/miljoeteknik-aatervinning", baseUrl:"https://www.mynewsdesk.com", type:"company", scope:"sweden", tier:2, trustScore:84, enabled:true, description:"Västsveriges regionala avfalls- och återvinningsaktör: investeringar, teknik, kapacitet och anläggningar." },
  { id:"prezero-news", name:"PreZero", listingUrl:"https://www.prezero.se/mina-sidor/nyheter/", baseUrl:"https://www.prezero.se", type:"competitor", scope:"sweden", tier:2, trustScore:82, enabled:true, competitorName:"PreZero", description:"Bolagets egna nyheter och investeringar." },
  { id:"ragnsells-news", name:"Ragn-Sells", listingUrl:"https://newsroom.ragnsells.se/", baseUrl:"https://newsroom.ragnsells.se", type:"competitor", scope:"sweden", tier:2, trustScore:82, enabled:true, competitorName:"Ragn-Sells", description:"Bolagets newsroom och pressmeddelanden." },
  { id:"stena-news", name:"Stena Recycling", listingUrl:"https://www.stenarecycling.com/sv/nyheter-insikter/nyheter/", baseUrl:"https://www.stenarecycling.com", type:"competitor", scope:"sweden", tier:2, trustScore:82, enabled:true, competitorName:"Stena Recycling", description:"Bolagets egna nyheter och insikter." },
  // v2.95 – bredare svensk och nordisk nyhetsbevakning. Verifierade listningssidor; fortsatt hård quality/provenance-gate efter intake.
  { id:"sorab-news", name:"SÖRAB", listingUrl:"https://www.sorab.se/", baseUrl:"https://www.sorab.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, description:"Regional avfallsaktör i norra Stockholmsregionen: anläggningar, behandling, kapacitet, mark, investeringar och entreprenader." },
  { id:"nsr-news", name:"NSR", listingUrl:"https://nsr.se/", baseUrl:"https://nsr.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, description:"Nordvästra Skånes Renhållnings AB: regional avfallshantering, anläggningar, insamling, behandling och förändringar." },
  { id:"june-avfall-news", name:"June Avfall & Miljö", listingUrl:"https://www.juneavfall.se/om-oss/aktuellt", baseUrl:"https://www.juneavfall.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, description:"Jönköping, Habo och Mullsjö: insamling, sortergårdar, taxor, förpackningsinsamling och regional kapacitet." },
  { id:"goteborg-kretslopp", name:"Göteborgs Stad – Kretslopp och vatten", listingUrl:"https://goteborg.se/kretsloppochvatten", baseUrl:"https://goteborg.se", type:"authority", scope:"sweden", tier:1, trustScore:100, enabled:true, description:"Kommunala beslut, taxor, kapacitet, kretsloppsparker, avfallsföreskrifter och upphandling i Göteborg." },
  { id:"dk-miljostyrelsen-news", name:"Miljøstyrelsen Danmark", listingUrl:"https://mst.dk/nyheder", baseUrl:"https://mst.dk", type:"authority", scope:"nordic", tier:1, trustScore:100, enabled:true, description:"Danska myndighetsnyheter om avfallstransporter, producentansvar, avfallsregler och cirkulär ekonomi med nordisk relevans." },
  { id:"norway-ssb-waste", name:"SSB Norge – Avfall", listingUrl:"https://www.ssb.no/natur-og-miljo/avfall", baseUrl:"https://www.ssb.no", type:"authority", scope:"nordic", tier:1, trustScore:100, enabled:true, description:"Norsk officiell avfallsstatistik och förändringar i materialflöden, farligt avfall och byggavfall." },
  { id:"nffa-news", name:"NFFA Norge", listingUrl:"https://www.nffa.no/aktuelt/", baseUrl:"https://www.nffa.no", type:"industry", scope:"nordic", tier:2, trustScore:88, enabled:true, description:"Norsk branschbevakning för farligt avfall, regelverk, behandlingsmarknad och myndighetsförändringar." },
  { id:"eu-circular-platform", name:"European Circular Economy Stakeholder Platform", listingUrl:"https://circulareconomy.europa.eu/platform/en/news-and-events/all-news", baseUrl:"https://circulareconomy.europa.eu", type:"eu", scope:"eu", tier:2, trustScore:94, enabled:true, description:"EU-initiativ, sekundära råvaror, förpackningar, plast, avfallstransporter och cirkulär marknadsutveckling." },
  { id:"eem-news", name:"Eskilstuna Energi & Miljö", listingUrl:"https://www.eem.se/om-oss/aktuellt", baseUrl:"https://www.eem.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, regions:["Södermanland"], description:"Eskilstuna/ReTuna: regionala investeringar, avfallstjänster, återbruk, anläggningar och förändringar." },
  { id:"lumire-news", name:"Lumire", listingUrl:"https://lumire.se/nyheter/", baseUrl:"https://lumire.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, regions:["Norrbotten"], description:"Luleå: avfallsinsamling, anläggningar, slam, återbruk och regionala kapacitetsförändringar." },
  { id:"avfall-skaraborg-news", name:"Avfall & Återvinning Skaraborg", listingUrl:"https://avfallskaraborg.se/Nyheter/", baseUrl:"https://avfallskaraborg.se", type:"company", scope:"sweden", tier:2, trustScore:88, enabled:true, regions:["Västra Götaland"], description:"13 medlemskommuner: avfallsföreskrifter, taxor, insamlingssystem, företagsbesök och regional avfallspolitik." },
  { id:"kretslopp-sydost-news", name:"Kretslopp Sydost", listingUrl:"https://kretsloppsydost.se/press/", baseUrl:"https://kretsloppsydost.se", type:"company", scope:"sweden", tier:2, trustScore:88, enabled:true, regions:["Kalmar","Jönköping"], description:"Sydöstra Sverige: anläggningar, närsortering, investeringar, insamling och kapacitetsförändringar." },
  { id:"gastrike-news", name:"Gästrike återvinnare", listingUrl:"https://gastrikeatervinnare.se/nyheter/", baseUrl:"https://gastrikeatervinnare.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, regions:["Gävleborg","Uppsala"], description:"Gästrikland och delar av norra Uppland: insamling, återvinningscentraler, textil, kapacitet och regionala förändringar." },
  { id:"boras-em-news", name:"Borås Energi och Miljö", listingUrl:"https://borasem.se/webb/privat/omoss/nyheter.4.3c2df772153e145280a37119.html", baseUrl:"https://borasem.se", type:"company", scope:"sweden", tier:2, trustScore:86, enabled:true, regions:["Västra Götaland"], description:"Borås: avfallstjänster, Sobacken, behandling, energiåtervinning, priser och anläggningsförändringar." },
  { id:"msva-news", name:"MittSverige Vatten & Avfall", listingUrl:"https://msva.se/", baseUrl:"https://msva.se", type:"company", scope:"sweden", tier:2, trustScore:84, enabled:true, regions:["Västernorrland","Gävleborg"], description:"Sundsvall, Timrå och Nordanstig: avfallsinsamling, återvinningscentraler, avgifter och regionala förändringar." },
];

export const wasteKeywords = [
  "avfall", "återvinn", "depon", "förpack", "plast", "textil", "material",
  "insamling", "producentansvar", "cirkul", "sortering", "biogas",
  "farligt avfall", "miljöbalk", "återbruk", "anläggning", "resurs",
  "fosfor", "batteri", "slam", "waste", "recycling", "circular economy",
  "packaging", "secondary raw material", "incineration", "landfill", "reuse",
  "miljötillstånd", "miljöprövning", "bygglov", "markköp", "etablering", "utsläpp",
  "förbränning", "återvinningscentral", "återvinningsstation", "avfallsanläggning",
];


// Rubrikord för intake/discovery. Dessa är medvetet bredare än kärnorden ovan;
// senare Article Validation + News Quality + Bid Relevance avgör om träffen faktiskt får visas.
export const wasteDiscoveryKeywords = [...wasteKeywords,
  "omlastning", "behandling", "kapacitet", "driftstart", "byggstart", "utbyggnad",
  "investering", "förvärv", "fusion", "etablering", "markanvisning", "detaljplan",
  "samråd", "kungörelse", "upphandling", "planerad upphandling", "upphandlingsplan", "rfi", "marknadsdialog", "tilldelning", "tilldelningsbeslut", "kontrakt", "uppdrag",
  "entreprenad", "entreprenörsbyte", "avtal", "avtalsstart", "option", "optionsår", "förlängning", "överprövning", "avbruten upphandling", "taxa", "avgift", "prisjustering", "prisändring",
  "producentansvar", "diwass", "secondary raw material", "waste shipment",
  "treatment", "facility", "plant", "contract", "award", "permit", "investment"
];
