export type WatchQuestion={id:string;question:string;createdAt:string;status:'active'|'closed'};
export type WatchQuestionTimeline={id:string;headline:string;competitors:string[];geographies:string[];latestSeen:string;stage:string;direction:string;escalationScore:number;facts:number;sourceClasses:string[];milestones:Array<{title:string;url:string;source:string;sourceClass:string;publishedAt:string}>;watchNext:string[]};
export type WatchQuestionAssessment={questionId:string;state:'strengthening'|'mixed'|'insufficient'|'cooling';supporting:WatchQuestionTimeline[];counter:WatchQuestionTimeline[];missing:string[];summary:string;guardrail:string};
function norm(v:string){return v.toLocaleLowerCase('sv-SE').replace(/[^a-z0-9åäö]+/g,' ').replace(/\s+/g,' ').trim();}
function toks(v:string){const stop=new Set(['ökar','minskar','är','har','på','väg','att','sin','sina','i','och','eller','med','för','den','det','de','ett','en','mer','fler','nya','ny']);return norm(v).split(' ').filter(x=>x.length>2&&!stop.has(x));}
function hash(v:string){let x=2166136261;for(let i=0;i<v.length;i++){x^=v.charCodeAt(i);x=Math.imul(x,16777619);}return (x>>>0).toString(16);}
export function createWatchQuestion(question:string,now=new Date()):WatchQuestion{return {id:`watchq-${hash(norm(question))}`,question:question.trim(),createdAt:now.toISOString(),status:'active'};}
export function assessWatchQuestion(q:WatchQuestion,timelines:WatchQuestionTimeline[]):WatchQuestionAssessment{
 const qt=toks(q.question); const nq=norm(q.question);
 const ranked=timelines.map(t=>{const hay=norm([t.headline,...t.competitors,...t.geographies,...t.sourceClasses,...t.watchNext].join(' '));const hits=qt.filter(x=>hay.includes(x)).length;let score=hits*14+t.escalationScore/12;if(/kapacitet|anläggning|etabler/.test(nq)&&/kapacitet|anläggning|etabler|bygg|tillstånd|samråd/.test(hay))score+=18;if(/upphandling|kontrakt|avtal/.test(nq)&&/upphandling|kontrakt|avtal|tilldel/.test(hay))score+=18;return {t,score,hits};}).filter(x=>x.hits>=1&&x.score>=20).sort((a,b)=>b.score-a.score);
 const related=ranked.slice(0,8).map(x=>x.t); const supporting=related.filter(x=>x.direction!=='cooling'); const counter=related.filter(x=>x.direction==='cooling');
 const sourceClasses=new Set(supporting.flatMap(x=>x.sourceClasses)); const missing:string[]=[]; if(!supporting.length)missing.push('Ingen aktuell signal ger ännu tydligt stöd för frågan.'); if(supporting.length&&sourceClasses.size<2)missing.push('Oberoende källklass saknas för starkare bekräftelse.'); if(supporting.length&&!supporting.some(x=>['formal-process','decision-or-award','execution'].includes(x.stage)))missing.push('Formell process, beslut eller genomförande saknas ännu.'); if(!counter.length)missing.push('Bevakly har ingen tydlig motbevisande/cooling-signal i aktuellt underlag.');
 const state:WatchQuestionAssessment['state']=!related.length?'insufficient':counter.length&&supporting.length?'mixed':counter.length?'cooling':supporting.some(x=>x.direction==='escalating')?'strengthening':'insufficient';
 const summary=state==='strengthening'?`Frågan stärks av ${supporting.length} relevant${supporting.length===1?' signal':'a signaler'}, men är inte bevisad.`:state==='mixed'?`Underlaget är blandat: ${supporting.length} stödjande och ${counter.length} avsvalnande signaler.`:state==='cooling'?`Aktuellt underlag pekar främst på avsvalning, inte bekräftelse.`:'Bevakly har ännu för lite relevant evidens för att bedöma frågan.';
 return {questionId:q.id,state,supporting,counter,missing,summary,guardrail:'En bevakningsfråga är en hypotes. Matchande signaler är evidens att granska – inte ett automatiskt ja-svar.'};
}
