import { Competitor, EventItem } from "./types";

export const events: EventItem[] = [
  {
    id: "evt-1",
    title: "Nya regler förändrar ansvar inom avfallshanteringen",
    summary: "Exempeldata: en regulatorisk förändring har identifierats och grupperats till en händelse med flera källor.",
    whyItMatters: "Kan påverka ansvarsfördelning, avtalsvillkor och kostnader för både kommuner och entreprenörer.",
    score: 94,
    importance: "Kritisk",
    category: "Lagstiftning",
    sourceCount: 6,
    primarySource: "Primär myndighetskälla",
    date: "2026-09-01",
    geography: "Sverige",
    demo: true,
  },
  {
    id: "evt-2",
    title: "Konkurrent ökar kapaciteten i Mellansverige",
    summary: "Exempeldata: investering, rekrytering och lokal närvaro har klustrats till en möjlig expansionssignal.",
    whyItMatters: "Flera oberoende signaler kan tyda på ökat konkurrenstryck i ett prioriterat geografiskt område.",
    score: 86,
    importance: "Mycket viktig",
    category: "Strategisk signal",
    company: "Exempelkonkurrent AB",
    sourceCount: 4,
    primarySource: "Företagskälla",
    date: "2026-08-31",
    geography: "Mellansverige",
    demo: true,
  },
  {
    id: "evt-3",
    title: "Ny upphandling inom insamling och transport",
    summary: "Exempeldata: en upphandling med tydlig bransch- och geografimatchning har prioriterats.",
    whyItMatters: "Kan innebära en konkret affärsmöjlighet och påverka konkurrensbilden i regionen.",
    score: 79,
    importance: "Mycket viktig",
    category: "Upphandling",
    sourceCount: 1,
    primarySource: "Offentlig upphandlingskälla",
    date: "2026-08-31",
    geography: "Örebro län",
    demo: true,
  },
  {
    id: "evt-4",
    title: "Ökad aktivitet kring textilavfall",
    summary: "Exempeldata: flera artiklar och myndighetsuppdateringar behandlar samma tema och visas som en samlad händelse.",
    whyItMatters: "Temat kan påverka framtida tjänsteutbud, investeringar och kundkrav.",
    score: 66,
    importance: "Relevant",
    category: "Marknad",
    sourceCount: 8,
    primarySource: "Branschkälla",
    date: "2026-08-30",
    geography: "Sverige / EU",
    demo: true,
  },
];

export const competitors: Competitor[] = [
  { id: "c1", name: "PreZero", priority: 1, activityScore: 82, latestSignal: "Ökad aktivitet i offentliga affärer", mentions30d: 14 },
  { id: "c2", name: "Ragn-Sells", priority: 1, activityScore: 78, latestSignal: "Investeringar och cirkulära materialflöden", mentions30d: 18 },
  { id: "c3", name: "Stena Recycling", priority: 2, activityScore: 71, latestSignal: "Teknik och materialåtervinning", mentions30d: 11 },
  { id: "c4", name: "Ohlssons", priority: 2, activityScore: 63, latestSignal: "Regional avtalsaktivitet", mentions30d: 7 },
];
