import assert from 'node:assert/strict';
import { extractArticle } from '../lib/intelligence/article.ts';
import { validateSourceArticle,nonNewsPageReason } from '../lib/intelligence/source-article-validation.ts';
import { buildNewsCardAnalysis } from '../lib/intelligence/news-card-analysis.ts';
import { makeWatchProfile } from '../lib/intelligence/watch-profiles.ts';
import { selectProfileNews,profileNewsMatch,visibleNewsGeographies } from '../lib/intelligence/profile-news-selection.ts';
import { competitorCoverageStatus } from '../lib/intelligence/competitor-coverage-status.ts';
import { extractSourceCandidates } from '../lib/intelligence/adapters.ts';
import { processDiscoveryResult } from '../lib/intelligence/discovery-result-pipeline.ts';
import { getIndustryProfile } from '../lib/intelligence/industries.ts';

const body='<p>Avfall och Miljö är Sveriges enda renodlade avfallstidning. I över 35 år har tidningen bevakat anläggningar och återvinning med fem nummer om året.</p>';
const magazine=extractArticle(`<h1>Tidningen Avfall och miljö - Avfall Sverige</h1><main>${body}</main><div>Senast uppdaterad - 2026-09-15</div>`);
assert.equal(magazine.publishedAt,null,'page update must not become publication');
assert.equal(magazine.modifiedAt,'2026-09-15T00:00:00.000Z');
assert.equal(validateSourceArticle({requestedTitle:magazine.title,url:'https://www.avfallsverige.se/aktuellt/tidningen-avfall-och-miljo/',article:magazine}).decision,'reject');
assert.equal(extractArticle('<h1>Informationssida</h1><span>Senast uppdaterad:</span><time datetime="2026-09-15">15 september 2026</time>').publishedAt,null);
assert.equal(extractArticle('<h1>Informationssida</h1><time itemprop="dateModified" datetime="2026-09-15">15 september 2026</time>').publishedAt,null);
const dated=extractArticle(`<meta property="article:published_time" content="2026-08-10"><meta property="article:modified_time" content="2026-09-15"><h1>Nytt insamlingsavtal</h1>${body}`);
assert.equal(dated.publishedAt,'2026-08-10T00:00:00.000Z','maintenance does not refresh old articles');
assert.equal(dated.modifiedAt,'2026-09-15T00:00:00.000Z');
assert.ok(nonNewsPageReason({title:'Nytt avtal',url:'https://example.com/nyheter/'}),'a hub requires a verified inline story');
assert.equal(nonNewsPageReason({title:'Nytt avtal',url:'https://example.com/nyheter/',allowInlineStory:true}),null);
const source=getIndustryProfile('waste').sources.find(s=>s.id==='ohlssons-news')!;
const inline=extractSourceCandidates(`<div class="aktuellt-item"><span class="post-date">2026-09-15</span><h3>Ohlssons vinner nytt insamlingsavtal</h3><p>Ohlssons har vunnit ett nytt insamlingsavtal som omfattar flera kommuner och 300 000 invånare med start i oktober.</p></div><div class="aktuellt-list"><p>Gammal anläggning utan koppling till det nya avtalet.</p></div>`,source);
assert.equal(inline.length,1);
assert.ok(inline[0].articleHtmlHint);
assert.ok(!inline[0].articleHtmlHint?.includes('Gammal anläggning'));
assert.equal(processDiscoveryResult({jobId:'test',targetId:'news:test',targetName:'Avfall',query:'avfall',title:magazine.title,url:'https://www.avfallsverige.se/aktuellt/tidningen-avfall-och-miljo/',publishedAt:new Date().toISOString(),snippet:magazine.textSample},{industryKeywords:['avfall']}).relevant,false);

const product=(title:string,factualSummary?:string)=>buildNewsCardAnalysis({title,factualSummary,watchKind:'ai-tools'});
assert.equal(product('Claude Frontier Academy: $100M to train 10,000 engineers').label,'Utbildning');
assert.equal(product('Barclays scales Claude to upgrade operations and improve client experience','The bank plans to expand its collaboration.').label,'Kundanvändning & samarbete');
assert.equal(product('4 ways to tackle household chores with Gemini','Gemini helps with meal planning.').label,'Användningstips');
assert.equal(product('Gemini 4 Argon: our next era of frontier intelligence','A new model launched today.').label,'Modelluppdatering');
assert.equal(product('New Gemini model is now available').label,'Modelluppdatering');
assert.equal(product('New pricing for API subscriptions').label,'Pris & villkor');
assert.equal(product('Claude discovers a novel enzyme system',"We're introducing a new life sciences research group and laboratory.").label,'Forskning');
assert.equal(product('Introducing Gemini 3.8 Live with Live Avatar').label,'Produktuppdatering');
assert.equal(product('Model training efficiency').level,'insufficient');
assert.equal(product('Our plans for Claude').level,'insufficient','plan and brand name are not product events');
assert.equal(buildNewsCardAnalysis({title:magazine.title,factualSummary:magazine.textSample,bidNewsRelevance:{tier:'A',label:'Direkt affärskritisk',themes:['Anläggning/kapacitet']}}).level,'insufficient','upstream labels are not evidence');
assert.equal(buildNewsCardAnalysis({title:'Årsrapport',factualSummary:'Bolaget driver en stor anläggning.'}).level,'insufficient');

const profile=makeWatchProfile({industry:'waste',market:'Sverige',regions:['Örebro län','Värmlands län'],themes:['Teknik & innovation'],actors:['Ragn-Sells']});
const news=(title:string,extra:Record<string,unknown>={})=>({title,url:'https://example.se/nyheter/'+encodeURIComponent(title),category:'Teknik & innovation',geographies:[],competitors:[],...extra});
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i Göteborg'),profile).matches,false);
assert.equal(profileNewsMatch(news('Ohlssons utökar närvaron i Göteborg',{category:'Konkurrent',factualSummary:'Ohlssons får ett nytt uppdrag i Göteborg.',geographies:['Sverige','Värmland']}),profile).matches,false,'page boilerplate cannot supply a false regional match');
assert.deepEqual(visibleNewsGeographies(news('Ohlssons utökar närvaron i Göteborg',{geographies:['Sverige','Värmland']})),['Göteborg']);
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i Karlstad'),profile).matches,true);
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i Karlstad',{factualSummary:'Från vår verksamhet i Göteborg.'}),profile).matches,true);
assert.equal(profileNewsMatch(news('Nya priser i Örebro',{category:'Marknad'}),profile).matches,false);
assert.equal(profileNewsMatch(news('Nytt kontrakt i Danmark',{competitors:['Ragn Sells']}),profile).matches,true);
assert.ok(profileNewsMatch(news('Ragn-Sells vinner nytt kontrakt i Göteborg',{competitors:['Ragn-Sells']}),profile).reasons.some(r=>r.includes('utanför')));
assert.equal(profileNewsMatch(news('Nya nationella avfallsregler',{url:'https://regeringen.se/pressmeddelanden/nya-regler',category:'Regelverk'}),profile).matches,true);
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i Danmark'),profile).matches,false);
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i Danmark'),{...profile,market:'Norden',regions:[]}).matches,true);
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i USA'),{...profile,market:'Europa',regions:[]}).matches,false);
assert.equal(profileNewsMatch(news('Ny sorteringsteknik i USA'),{...profile,market:'Globalt',regions:[]}).matches,true);
assert.equal(selectProfileNews([news('Ny sorteringsteknik i Örebro'),news('Ny sorteringsteknik i Göteborg')],profile).length,1);
assert.equal(profileNewsMatch(news('Nya priser i Örebro',{category:'Marknad'}),{...profile,themes:[]}).matches,true);

assert.equal(competitorCoverageStatus('PreZero',[],[]).label,'Ingen direktkälla kontrollerad');
assert.equal(competitorCoverageStatus('PreZero',[{id:'p',name:'PreZero',ok:false}],[]).label,'Ofullständig kontroll');
assert.equal(competitorCoverageStatus('PreZero',[{id:'p',name:'PreZero',ok:true,articleChecks:2,articleFailures:1}],[]).label,'Ofullständig kontroll');
assert.equal(competitorCoverageStatus('PreZero',[{id:'p',name:'PreZero',ok:true,articleChecks:2}],[]).label,'Inga godkända nyheter i lästa artiklar');
assert.equal(competitorCoverageStatus('PreZero',[{id:'p',name:'PreZero',ok:true}],[]).label,'Källsidan nådd – artikeltäckning ej verifierad');
assert.equal(competitorCoverageStatus('PreZero',[{id:'p',name:'PreZero',ok:false}],[]).lastSuccessfulCheck,undefined);
console.log('v3.43 user feedback regressions: PASS');
