import {assessCrossSignalEscalation,type CrossSignalEvidence} from '../lib/intelligence/cross-signal-escalation.ts';
const e=(stage:CrossSignalEvidence['stage'],sourceClass:string,source:string):CrossSignalEvidence=>({stage,sourceClass,source,publishedAt:'2026-09-01'});
const cases=[
 {name:'many weak mentions stay weak',items:[e('first-signal','news','A'),e('first-signal','jobs','B'),e('first-signal','news','C'),e('first-signal','jobs','D')],check:(x:ReturnType<typeof assessCrossSignalEscalation>)=>x.scoreCap===69&&!x.escalating&&x.corroborationBonus<=4},
 {name:'land plus consultation escalates carefully',items:[e('first-signal','municipal','Kommun'),e('formal-process','environmental','Länsstyrelsen'),e('corroborating','news','Tidning')],check:(x:ReturnType<typeof assessCrossSignalEscalation>)=>x.escalating&&x.progressionDepth===3&&x.scoreCap===84&&x.corroborationBonus>=10},
 {name:'formal plus decision may reach high attention',items:[e('first-signal','municipal','Kommun'),e('formal-process','planning','Kommun plan'),e('decision-or-award','authority','Myndighet')],check:(x:ReturnType<typeof assessCrossSignalEscalation>)=>x.escalating&&x.scoreCap===94&&x.corroborationBonus>=14},
 {name:'execution after earlier stages is strongest progression',items:[e('first-signal','jobs','Bolag'),e('formal-process','environmental','Länsstyrelsen'),e('decision-or-award','municipal','Kommun'),e('execution','news','Tidning')],check:(x:ReturnType<typeof assessCrossSignalEscalation>)=>x.escalating&&x.scoreCap===100&&x.corroborationBonus===18},
 {name:'same-source repetition is not independent escalation',items:[e('first-signal','news','Same'),e('formal-process','news','Same'),e('formal-process','news','Same')],check:(x:ReturnType<typeof assessCrossSignalEscalation>)=>!x.escalating&&x.distinctSources===1},
 {name:'replicated formal mentions do not invent decision',items:[e('formal-process','news','A'),e('formal-process','media','B'),e('formal-process','authority','C')],check:(x:ReturnType<typeof assessCrossSignalEscalation>)=>!x.escalating&&x.scoreCap===84&&!x.distinctStages.includes('decision-or-award')},
];
let pass=0;for(const c of cases){const x=assessCrossSignalEscalation(c.items);if(c.check(x))pass++;else console.log('FAIL',c.name,x);}if(pass!==cases.length)throw new Error(`${pass}/${cases.length} cross-signal cases passed`);console.log(`PASS ${pass}/${cases.length} cross-signal escalation cases`);
